/*
 * Copyright (C) 2025 European Union
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence"); You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an
 * "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the Licence for
 * the specific language governing permissions and limitations under the Licence.
 */

package eu.europa.ec.itb.shacl.standalone;

import eu.europa.ec.itb.validation.commons.jar.ValidationInput;

import java.io.File;

/**
 * Captures the provided input and the input file name. The file name may be one
 * generated by the validator in case the input is not provided from the file system.
 */
public class ShaclValidationInput extends ValidationInput {

    private final String contentSyntax;

    /**
     * Constructor.
     *
     * @param inputFile The input file.
     * @param filename The file name.
     * @param contentSyntax The RDF syntax of the provided input.
     */
    public ShaclValidationInput(File inputFile, String filename, String contentSyntax) {
        super(inputFile, filename);
        this.contentSyntax = contentSyntax;
    }

    /**
     * @return The RDF syntax of the provided input.
     */
    public String getContentSyntax() {
    	return this.contentSyntax;
    }
}
