package eu.europa.ec.itb.shacl.standalone;

import eu.europa.ec.itb.validation.commons.jar.ValidationInput;

import java.io.File;

/**
 * Captures the provided input and the input file name. The file name may be one
 * generated by the validator in case the input is not provided from the file system.
 */
public class ShaclValidationInput extends ValidationInput {

    private final String contentSyntax;

    /**
     * Constructor.
     *
     * @param inputFile The input file.
     * @param filename The file name.
     * @param contentSyntax The RDF syntax of the provided input.
     */
    public ShaclValidationInput(File inputFile, String filename, String contentSyntax) {
        super(inputFile, filename);
        this.contentSyntax = contentSyntax;
    }

    /**
     * @return The RDF syntax of the provided input.
     */
    public String getContentSyntax() {
    	return this.contentSyntax;
    }
}
