package eu.europa.ec.itb.shacl.standalone;

import java.io.File;

/**
 * Captures the provided input and the input file name. The file name may be one
 * generated by the validator in case the input is not provided from the file system.
 */
public class ValidationInput {

    private final File inputFile;
    private final String validationType;
    private final String filename;
    private final String contentSyntax;

    /**
     * Constructor.
     *
     * @param inputFile The input file.
     * @param validationType The requested validation type.
     * @param filename The file name.
     * @param contentSyntax The RDF syntax of the provided input.
     */
    public ValidationInput(File inputFile, String validationType, String filename, String contentSyntax) {
        this.inputFile = inputFile;
        this.validationType = validationType;
        this.filename = filename;
        this.contentSyntax = contentSyntax;
    }

    /**
     * @return The input file.
     */
    public File getInputFile() {
        return inputFile;
    }

    /**
     * @return The requested validation type.
     */
    public String getValidationType() {
        return validationType;
    }

    /**
     * @return The file name.
     */
    public String getFilename() {
    	return filename;
    }

    /**
     * @return The RDF syntax of the provided input.
     */
    public String getContentSyntax() {
    	return this.contentSyntax;
    }
}
